### PR TITLE
Pratyush umass working

### PR DESCRIPTION
**Pull request by pratyush06853**
this branch has the fall time error estimation and some asthetics changes to plot the iv-didv graphs

### CODE REVIEW

**Comment by serfass** [comment]
I would suggest you merge first master into your branch and resolve conflicts before merging to master. Also best is to finalize  error calculations before merging. Thanks!

**Comment by pratyush06853** [comment]
Will do that. Thanks! I will delete that merge request.

**Comment by magsreed** [comment]
Sorry Praytush, I merged some stuff we changed into master, so there are new conflicts. 
You will have to resolve conflicts in your branch before we merge. Before we approve stuff, could we see some test plots of the errors with data and values to make sure everything is making sense?

**Comment by pratyush06853** [comment]
Hi Maggie,
Actually, I tried to delete the merge request, but I wasn't able to do it.

The fall time errors were not being computed using the full covariance
matrix and also the fall_time errors for the didv_priors stuff would need
to have more algebra. I am working on it; once that is done I will let you
all know.

Thanks
Pratyush

**Pull request closed without merging**
