### PR TITLE
Feature/photon calibration

### PR DESCRIPTION
**Pull request by rkromani**
Added a PhotonCalibration class to QETPy including demo notebooks. The basic features of PhotonCalibration are as follows:

- Fitting a spectrum from a photon calibration (i.e. Possion distributed Gaussians)
- Selecting events from this spectrum for analysis
- Subtracting crosstalk
- Converting the pulses into the power domain using a dIdV fit result object
- Fitting the pulses in the frequency and power domain using one of a variety of models
- Displaying the results, including calculating current domain templates, and phonon collection efficiencies with uncertainties

### CODE REVIEW

**Comment by serfass** [comment]
It looks like a great package!  I am wondering however why you have it in QETpy rather than detanalysis?  QETpy is meant to be a set of utilities/tools that  other packages such detprocess/pytesdaq/detanalysis are using.  However, in your code you include analyzer object and import detanalysis. That seems to break a bit the organization (?)

**Comment by rkromani** [comment]
It seems like a dIdV like analysis tool, and all the dIdV code is in qetpy…
I feel like detanalysis is more for doing analysis on continuous data. This
I wanted to be something that tells us about the physics of the detector
rather than what we see using the detector.

That said if you have strong feelings, I’m fine moving it.

**Comment by serfass** [comment]
Here is the way I would describe the packages:

- QETpy:  tools to calculate TES related quantities (dIdV, noise, etc) and trace fitting routines. This is the most public python module and also used outside Spice/Herald (in particular I am using it for SuperCDMS but  other people are using it outside CDMS/Spice-Herald). So the package should be completely independent of the type of raw data and  Spice/Herald packages such as detanalysis and detprocess, in particular arguments should for example numpy or dataframes and not Spice/Herald objects such as detanalysis objects. 

-detanalysis: analysis of Spice/Herald data  processed with detprocess and eventually tools to interface analysis with Spice/Herald raw data (taken with pytesdaq). This could include utilities to fit RQ distribution for example.

-deprocess: processing of Spice/Herald raw data (IV/dIdV/continuous/etc), using QETpy for main calculations and fitting. Modules used for processing should be usable on stand alone to analyze raw data. 


So anyway,  although I agree that some functions could be part of QETpy, my main concern is that it would bring Spice/Herald specific packages into QETpy, which I am somewhat strongly against.  So unless it can be made more general, and in particular avoid  using detanalysis's Analyzer objec and  SemiAutocuts, etc by splitting the functionality and loading events outside QETpy, I think we should put it in detanalysis (or alternatively its own new Spice/Herald package if you prefer).

**Comment by serfass** [comment]
As an aside we  should look at the error with python 3.7.

**Comment by magsreed** [comment]
Was there any further update on the python 3.7 error and also where we want this package located?

**Comment by serfass** [comment]
Sorry I haven't been following up.  Should we meet on zoom with Roger and briefly discuss about it?

**Comment by magsreed** [comment]
Closing this as this was moved from QETpy to det.

**Pull request closed without merging**
